# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27-pytest4
      - python: 3.4
        env: TOX_ENV=py34-pytest4
      - python: 3.5
        env: TOX_ENV=py35-pytest4
      - python: 3.5
        env: TOX_ENV=py35-pytest5
      - python: 3.6
        env: TOX_ENV=py36-pytest4
      - python: 3.6
        env: TOX_ENV=py36-pytest5
      - python: 3.7
        env: TOX_ENV=py37-pytest4
      - python: 3.7
        env: TOX_ENV=py37-pytest5
      - python: pypy
        env: TOX_ENV=pypy-pytest4

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
