# Config file for automatic testing at travis-ci.org

os: linux
dist: focal
sudo: false
language: python

matrix:
    include:
      - python: 3.6
        env: TOX_ENV=py36-pytest5
      - python: 3.6
        env: TOX_ENV=py36-pytest6
      - python: 3.7
        env: TOX_ENV=py37-pytest5
      - python: 3.7
        env: TOX_ENV=py37-pytest6
      - python: 3.8
        env: TOX_ENV=py38-pytest5
      - python: 3.8
        env: TOX_ENV=py38-pytest6
      - python: 3.9
        env: TOX_ENV=py39-pytest5
      - python: 3.9
        env: TOX_ENV=py39-pytest6
      - python: "3.10.1"
        env: TOX_ENV=py310-pytest5
      - python: "3.10.1"
        env: TOX_ENV=py310-pytest6

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
